train: /content/drive/MyDrive/colab_data/odt/data/train/images
val: /content/drive/MyDrive/colab_data/odt/data/valid/images
test: /content/drive/MyDrive/colab_data/odt/data/test/images

nc: 8
names: ['Parking', 'Speed Limit', 'Speed limit', 'Traffic-Light', 'cross walk', 'speed limit', 'speed- limit', 'stop']

roboflow:
  workspace: stop-sign-ymxgd
  project: stop-sign-guuwz
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/stop-sign-ymxgd/stop-sign-guuwz/dataset/1